#!/usr/bin/env node

var http      = require('http'),
    tilelive  = require('tilelive'),
    mbtiles   = require('mbtiles'),
    minimist  = require('minimist'),
    fs        = require('fs'),
    path      = require('path'),
    express   = require('express')

const argv     = minimist(process.argv.slice(2)),
      tiledir  = argv.mbtiles,
      styledir = argv.styles,
      port     = argv.port || 4326,
      pattern  = /^\/(\d+)\/(\d+)\/(\d+).pbf$/,
      app      = express()

// This script requires a tile directory and style directory
if(!tiledir || !styledir)
  return console.log('Usage: ' + path.basename(__filename) +
    ' --mbtiles /path/to/mbtiles/parent/directory' +
    ' --styles /path/to/styles/parent/directory' +
    ' --port [optional port | 4326]')

mbtiles.registerProtocols(tilelive)

// Add support for CORS
app.use(cors)

// Serve files from style directory as static assets
app.use('/styles', express.static(styledir))

// Serve the requested tile from the requested mbtiles tileset
app.get('/tiles/:name/:z/:x/:y.pbf', function(req, res) {
  var params = req.params,
      name    = params.name,
      z       = params.z,
      x       = params.x,
      y       = params.y,
      tileurl = 'mbtiles://' + path.resolve(path.join(tiledir, name + '.mbtiles'))

  console.log('Loading: %s.  Tile z: %s, x: %s, y: %s', tileurl, z, x, y)

  tilelive.load(tileurl, function(err, source) {
    source.getTile(z, x, y, function(err, tile, headers) {
      if(err) return res.status(404).send(err.message + ' in ' + name)
      res.set(headers)
      return res.end(tile)
    })
  })

})

// Start the server on the given port
var server = app.listen(port, function() {
  var addr = server.address(),
      host = addr.address,
      port = addr.port

  console.log('Cartile at your service on //%s:%s', host, port)
})

// Support Cross-Origin Resource Sharing
//
// req - An express request
// res - An express response
// next - object for passing control to next handler
//
// Returns nothing
function cors(req, res, next) {
  res.header('Access-Control-Allow-Origin', '*')
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept')
  next()
}
